name: Docker Image CI - cruise control

on:
  push:
    paths:
      - 'docker-cruise-control/**'
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: yvlasenko
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Build the Docker image
      working-directory: docker-cruise-control/
      run: |
        docker build . --file Dockerfile --tag yvlasenko/cruise-control:latest

    - name: Docker Push
      working-directory: docker-cruise-control/
      run: docker push yvlasenko/cruise-control
