name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: yvlasenko
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
    - name: Build the Docker image
      uses: docker/build-push-action@v2
      with:
        context: docker-kafka
        file: ./Dockerfile
        push: true
        tags: |
            yvlasenko/kafka:latest
